apiVersion: v1
kind: Pod

metadata:
  name: my-app-pod
  labels:
    app: myapp
    type: rninx

spec:
  containers:
    - name: nginx-container
      image: nginx

    - name: backend
      image: redis
