apiVersion: v1
kind: ReplicationController
metadata:
  name: red

spec:
  replicas: 3
  template:
    metadata:
      labels:
        colour: red
    spec:
         containers:
          - image: nginx
            name: red-nginxs
            ports:
                - containerPort: 80

---
apiVersion: v1
kind: ReplicationController
metadata:
  name: green-replication-controller

spec:
  replicas: 3
  template:
    metadata:
      labels:
        colour: green
    spec:
      containers:
        - image: nginx
          name: green-nginxs
          ports:
            - containerPort: 80
---

apiVersion: v1
kind: ReplicationController
metadata:
  name: blue

spec:
  replicas: 4
  template:
    metadata:
      labels:
        colour: blue
    spec:
      containers:
        - image: nginx
          name: blue-nginxs
          ports:
            - containerPort: 80


